name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django

      - name: Deploy to VM
        env:
          HOST: ${{ secrets.VM_HOST }}
          USERNAME: ${{ secrets.VM_USERNAME }}
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          echo "${SSH_KEY}" | base64 -d > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          cd /path/to/your/project
          git pull origin main
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart your_django_service
          EOF
