name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install django

    - name: Deploy to VM
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no -r . azureuser@20.55.75.96:/home/azureuser/myproject || exit 1
        ssh -i private_key.pem -o StrictHostKeyChecking=no azureuser@20.55.75.96 << 'EOF'
          cd /home/azureuser/myproject || exit 1
          sudo python3 manage.py migrate || exit 1
          sudo python3 manage.py collectstatic --noinput || exit 1
          sudo systemctl restart myproject.service || exit 1  # Ensure a systemd service is set up
        EOF
